# Generated by Django 5.0.3 on 2024-06-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highrise_app', '0003_sagemitra_new_sm_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagemitra',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
